
server:
  error:
    whitelabel:
      enabled: false
  port: 8080

logging:
  level:
    org:
      springframework:
        http: debug
      powerimo: info

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    open-in-view: false