
server:
  error:
    whitelabel:
      enabled: false
  port: 8080

logging:
  level:
    org:
      springframework: info
      powerimo: info

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password